### ISSUE TITLE
Milestone 2 TODO List

### ISSUE THREAD

**Issue by mru4913** [UBC-MDS/Self-perceived-Difficulty-of-DSCI-512-Analysis#27]
Tasks
---
- [x] 1.  Create our survey 
- [x] 2. Collect data from other MDS students, 554 TAs and lab instructor
- [x] 3. Perform some exploratory data analysis (EDA) on your survey data
- [x] 3.1 EDA 1 
- [x] 3.2 EDA 2 
- [x] 3.3 EDA 3
- [x] 3.4 EDA 4 
- [x] 4. Release v2.0 (Make sure you link to a copy of this EDA in the README of your Github repo for this Milestone.)

Notes 
---
We are going to use R to perform the test. We will use .Rmd for EDA, please also include the rendered document in our Github repo so we can easily read the output of the run code as well.

1. In order to improve our coding format, it is better to limit to 100 characters per line. For further information, please read https://stackoverflow.com/questions/88942/why-does-pep-8-specify-a-maximum-line-length-of-79-characters
2. To toggle the warning line in Studio. https://support.rstudio.com/hc/en-us/community/posts/207625357-Toggle-80-character-warning-line
