### ISSUE TITLE
To-do's for milestone 1

### ISSUE THREAD

**Issue by tungpatrick** [UBC-MDS/Self-perceived-Difficulty-of-DSCI-512-Analysis#6]
- [x] Identify the question that your team in interested in answering with the survey. The aim of the survey should be to try to answer one specific and testable question. 

- [x] Identify the other questions you plan to ask in your survey to identify confounding variables and justify/explain why you plan to include them.

- [x] Describe how you plan to analyze the survey results (e.g., what statistical test(s) do you plan to employ?).

- [x] Discuss the aspects of the UBC Office of Research Ethics document on Using Online Surveys that are relevant to your proposed survey.

**Comment by tungpatrick** [comment]
Survey tool: https://ubc.qualtrics.com
